

/* 1 */ 

CREATE TABLE DEPT( DEPTNO NUMBER(2), DNAME CHAR(20),LOC CHAR(20),
			CONSTRAINT DEPT_PK PRIMARY KEY (DEPTNO),                   
			CONSTRAINT DEPT_CK CHECK (DNAME IN ('ACCOUNTING','RESEARCH','SALES','OPERATIONS'))
	); 

/* 2 */ 
INSERT INTO DEPT VALUES (1, 'ACCOUNTING', 'ESSAOUIRA');
INSERT INTO DEPT VALUES (2, 'RESEARCH', 'AGADIR');
INSERT INTO DEPT VALUES (3, 'SALES', 'PARIS');
INSERT INTO DEPT VALUES (4, 'OPERATIONS', 'ROME');

/* 3 */ 


CREATE TABLE EMP AS SELECT * FROM SCOTT.EMP;


/* 4 */ 

INSERT INTO EMP VALUES (7369, 'Bidon', NULL, NULL, NULL, NULL, NULL, NULL);

/* 5 */ 

ROLLBACK ;

/* 6 */ 

ALTER TABLE EMP ADD CONSTRAINT EMP_PK PRIMARY KEY(EMPNO);
ALTER TABLE EMP ADD CONSTRAINT EMP_FK FOREIGN KEY(DEPTNO) REFERENCES DEPT(DEPTNO);
ALTER TABLE EMP ADD CONSTRAINT EMP_FK FOREIGN KEY(MGR) REFERENCES EMP(EMPNO);

/* 7 */ 
  # (ne fonctionne pas ) la clé primaire EMPNO déja existée dans la table
  INSERT INTO EMP VALUES (7369, 'WILSON', 'MANAGER', 7839, '17/11/91', 3500.00, 600.00, 10) ;  
  # (ne fonctionne pas ) La valeur 50 (DEPTNO)  n'existe pas dans la table DEPT 
  INSERT INTO EMP VALUES (7657, 'WILSON', 'MANAGER', 7839, '17/11/91', 3500.00, 600.00, 50) ; 
  # (ne fonctionne pas ) Le manager de numéro 7000 (MGR) n'existe pas comme employée 
  INSERT INTO EMP VALUES (7657, 'WILSON', 'MANAGER', 7000, '17/11/91', 3500.00, 600.00, 10) ; 
  #Correct
  INSERT INTO EMP VALUES (7657, 'WILSON', 'MANAGER', 7839, '17/11/91', 3500.00, 600.00, 10) ;

/* 8 */ 

COMMIT; 


# Mise à jour de la base de donnée #

/* 1 */

UPDATE DEPT SET LOC='PITTSBURGH' WHERE DNAME= 'SALES' ;

/* 2 */ 

UPDATE EMP SET SAL=SAL*1.1 WHERE COMM>0.5*SAL;

/* 3 */ 

UPDATE EMP SET COMM = (SELECT AVG(COMM) FROM EMP) 
	  WHERE HIREDATE<'01/01/82' AND COMM IS NULL ;

/* 4 */ 

ROLLBACK; 

/* 5 */ 


DELETE FROM DEPT WHERE DEPTNO = 20; 


/* 1 */ 
SELECT ENAME, SAL, COMM, SAL+COMM FROM EMP WHERE JOB='SALESMAN';
/* 2 */ 
SELECT ENAME FROM EMP ORDER BY COMM/SAL DESC;
/* 3 */ 
SELECT ENAME FROM EMP WHERE COMM<.25*SAL;
/* 4 */ 
SELECT COUNT(EMPNO) FROM EMP WHERE DEPTNO=10;
/* 5 */ 
SELECT COUNT(EMPNO) FROM EMP WHERE COMM IS NOT NULL;
/* 6 */ 
SELECT COUNT(DISTINCT JOB) FROM EMP;
/* 7 */ 
SELECT JOB, AVG(SAL) FROM EMP GROUP BY JOB;
/* 8 */ 
SELECT SUM(E.SAL) FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO AND DNAME='SALES';  
/* 9 */ 
SELECT E.ENAME, D.DNAME FROM EMP E , DEPT D WHERE E.DEPTNO = D.DEPTNO; 
/* 10 */ 
SELECT ENAME, JOB, SAL FROM EMP WHERE SAL = (SELECT MAX(SAL) FROM EMP);
/* 11 */ 
SELECT ENAME FROM EMP WHERE SAL>(SELECT SAL FROM EMP WHERE ENAME='JONES');
/* 12 */ 
SELECT ENAME FROM EMP WHERE JOB=(SELECT JOB FROM EMP WHERE ENAME='JONES') AND ENAME<>'JONES'; 
/* 13 */ 
SELECT ENAME FROM EMP WHERE MGR=(SELECT MGR FROM EMP WHERE ENAME='CLARK')                      
AND ENAME<>'CLARK';
/* 14 */ 
SELECT ENAME FROM EMP WHERE (JOB, MGR) IN (SELECT JOB, MGR FROM EMP WHERE ENAME='TURNER') 
AND ENAME<>'TURNER';
/* 15 */ 
SELECT ENAME FROM EMP WHERE HIREDATE < ALL (SELECT HIREDATE FROM EMP WHERE DEPTNO=10);
/* 16 */ 
SELECT E.ENAME, M.ENAME FROM EMP E, EMP M 
WHERE E.MGR=M.EMPNO;
/* 17 */ 
SELECT E.ENAME FROM EMP E, EMP M WHERE E.MGR = M.EMPNO AND E.DEPTNO<>M.DEPTNO;