

CREATE TABLE PIECE ( NOP NUMBER(3),
           DESIGNATION CHAR(20),
           COULEUR CHAR(15),
           POIDS NUMBER(5,2) 
) ;

CREATE TABLE SERVICE (NOS NUMBER(3),
            INTITULE CHAR(20),
            LOCALISATION CHAR(30) 
) ;

CREATE TABLE ORDRE ( NOP NUMBER(3),
             NOS NUMBER(3),
           QUANTITE NUMBER(3) 
) ;

CREATE TABLE NOMENCLATURE ( NOPA NUMBER(3),
                NOPC NUMBER(3),
                QUANTITE NUMBER(3)
) ;



/* 1 */
INSERT INTO PIECE VALUES (1, 'Piece1', 'Vert', 17) ;
INSERT INTO PIECE VALUES (2, 'Piece2', 'Jaune', 8) ;
/* 2 */
INSERT INTO SERVICE VALUES (1, 'item1', 'paris') ;
INSERT INTO SERVICE VALUES (2, 'item2', 'lyon') ;
/* 3 */
INSERT INTO ORDRE VALUES (1, 3, 17) ;
INSERT INTO ORDRE VALUES (2, 4, 8) ;
/* 4 */
INSERT INTO NOMENCLATURE VALUES (5, 3 , 17) ;
INSERT INTO NOMENCLATURE VALUES (7, 5 , 8) ;
/* 5 */
ALTER TABLE PIECE
ADD CONSTRAINT PIECE_pk PRIMARY KEY (NOP) ;

ALTER TABLE SERVICE
ADD CONSTRAINT SERVICE_pk PRIMARY KEY (NOS) ;

ALTER TABLE ORDRE
ADD CONSTRAINT ORDRE_pk PRIMARY KEY (NOP, NOS) ;

ALTER TABLE ORDRE
ADD CONSTRAINT ORDRE_fk FOREIGN KEY (NOP) REFERENCES PIECE (NOP) ;

ALTER TABLE ORDRE
ADD CONSTRAINT ORDRE_fk FOREIGN KEY (NOS) REFERENCES SERVICE (NOS) ;

ALTER TABLE NOMENCLATURE
ADD CONSTRAINT NOM_pk PRIMARY KEY (NOPA, NOPC) ;

ALTER TABLE NOMENCLATURE
ADD CONSTRAINT NOM_fk FOREIGN KEY (NOPA) REFERENCES PIECE (NOP) ;

ALTER TABLE NOMENCLATURE
ADD CONSTRAINT NOM_fk FOREIGN KEY (NOPC) REFERENCES PIECE (NOP) ;

ALTER TABLE PIECE
ADD CONSTRAINT PIECE_ck CHECK (COULEUR IN ('ROUGE', 'VERTE', 'BLEUE', 'JAUNE') ;


/* 1 */ 

ALTER TABLE PIECE 
MODIFY (DESIGNATION CHAR(30)) ;

ALTER TABLE SERVICE 
MODIFY (INTITULE CHAR(30)) ;

/* 2 */
ALTER TABLE SERVICE 
MODIFY (LOCALISATION CHAR(20))
/* 3 */ 
ALTER TABLE SERVICE 
ADD (DIRECTEUR CHAR(50)) ;
/* 4 */ 
ALTER TABLE SERVICE 
DROP UNIQUE (LOCALISATION) ;
/* 5 */ 
ALTER TABLE PIECE DROP PRIMARY KEY ;
/* 6 */
ALTER TABLE PIECE DROP CONSTRAINT PIECE_ck ;
/* 7 */ 
DROP TABLE NOMENCLATURE ;
/* 8 */ 
DROP TABLE ORDRE CASCADE CONSTRAINTS ;
SELECT * FROM PIECE ;
SELECT * FROM SERVICE ;